# Generated by Django 5.1.6 on 2025-02-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscanpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='labeled_contains_nrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
