# Generated by Django 5.1.6 on 2025-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscanpro', '0002_scanrecord_labeled_contains_nrl'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='missing_scans/'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
    ]
