# Generated by Django 5.1.6 on 2025-02-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscanpro', '0003_scanrecord_image_scanrecord_is_manual_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
